![imagen](./img/ejercicios.png)

# Ejercicio SQL
Para este ejercicio usaremos una base de datos de Pokemon. **Asegúrante que tienes el CSV "pokemon.csv" en la misma carpeta donde está este Notebook**. Realiza los siguientes apartados:

1. Obten una tabla con todos los campos
2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
4. ¿Cuales son todos los "Type 1" diferentes?
5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
7. Obtén una tabla con los pokemon legendarios
8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
11. ¿Cuál es el pokemon con el ataque más alto?
12. ¿Cuál es la media de la defensa de todos los pokemon?
13. ¿Cuál es la media de la defensa por generación?
14. Calcula el máximo HP por "Type 1"

**NOTA**: se recomienda añadir un `LIMIT 5` en la mayoría de apartados para evitar grandes outputs de las queries.

In [102]:
# Importamos paquetes
import pandas as pd
import sqlite3
cnx = sqlite3.connect(':memory:')

# Importamos datos de un CSV
df = pd.read_csv('pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [103]:
# Pasamos el DataFrame de Pandas a SQL
df.to_sql('pokemon', con=cnx, if_exists='append', index=False)

# Definimos la función para hacer queries.
def sql_query(query):
    return pd.read_sql(query, cnx)

In [104]:
# 1. Obten una tabla con todos los campos
query = '''
SELECT *
FROM pokemon
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [105]:
# 2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
query = '''
SELECT name,'Type 1','Type 2'
FROM pokemon
'''

sql_query(query)

                      Name 'Type 1' 'Type 2'
0                Bulbasaur   Type 1   Type 2
1                  Ivysaur   Type 1   Type 2
2                 Venusaur   Type 1   Type 2
3    VenusaurMega Venusaur   Type 1   Type 2
4               Charmander   Type 1   Type 2
..                     ...      ...      ...
795                Diancie   Type 1   Type 2
796    DiancieMega Diancie   Type 1   Type 2
797    HoopaHoopa Confined   Type 1   Type 2
798     HoopaHoopa Unbound   Type 1   Type 2
799              Volcanion   Type 1   Type 2

[800 rows x 3 columns]

In [106]:
# 3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
query = '''
SELECT name Nombre,'Type 1' "Tipo 1",'Type 2' "Tipo 2"
FROM pokemon
'''

sql_query(query)

                    Nombre  Tipo 1  Tipo 2
0                Bulbasaur  Type 1  Type 2
1                  Ivysaur  Type 1  Type 2
2                 Venusaur  Type 1  Type 2
3    VenusaurMega Venusaur  Type 1  Type 2
4               Charmander  Type 1  Type 2
..                     ...     ...     ...
795                Diancie  Type 1  Type 2
796    DiancieMega Diancie  Type 1  Type 2
797    HoopaHoopa Confined  Type 1  Type 2
798     HoopaHoopa Unbound  Type 1  Type 2
799              Volcanion  Type 1  Type 2

[800 rows x 3 columns]

In [107]:
# 4. ¿Cuales son todos los "Type 1" diferentes?
query = '''
SELECT DISTINCT "Type 1"
FROM pokemon
'''

sql_query(query)

      Type 1
0      Grass
1       Fire
2      Water
3        Bug
4     Normal
5     Poison
6   Electric
7     Ground
8      Fairy
9   Fighting
10   Psychic
11      Rock
12     Ghost
13       Ice
14    Dragon
15      Dark
16     Steel
17    Flying

In [108]:
# 5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
query = '''
SELECT DISTINCT "Type 1", "Type 2"
FROM pokemon
'''

sql_query(query)

      Type 1  Type 2
0      Grass  Poison
1       Fire     NaN
2       Fire  Flying
3       Fire  Dragon
4      Water     NaN
..       ...     ...
149    Ghost   Grass
150   Flying  Dragon
151  Psychic   Ghost
152  Psychic    Dark
153     Fire   Water

[154 rows x 2 columns]

In [109]:
# 6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
query = '''
SELECT "Type 1"
FROM pokemon
WHERE "Type 1" = "Water";
'''

sql_query(query)

    Type 1
0    Water
1    Water
2    Water
3    Water
4    Water
..     ...
107  Water
108  Water
109  Water
110  Water
111  Water

[112 rows x 1 columns]

In [110]:
# 7. Obtén una tabla con los pokemon legendarios
query = '''
SELECT "legendary" "Legendarios", "name" "Nombre"
FROM pokemon
WHERE "legendary" > 0
'''

sql_query(query)

    Legendarios               Nombre
0             1             Articuno
1             1               Zapdos
2             1              Moltres
3             1               Mewtwo
4             1  MewtwoMega Mewtwo X
..          ...                  ...
60            1              Diancie
61            1  DiancieMega Diancie
62            1  HoopaHoopa Confined
63            1   HoopaHoopa Unbound
64            1            Volcanion

[65 rows x 2 columns]

In [111]:
# 8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
query = '''
SELECT "Name" "Nombre", "Type 1" "Tipo 1"
FROM pokemon
WHERE "Type 1" = "Fire"
'''

sql_query(query)

                       Nombre Tipo 1
0                  Charmander   Fire
1                  Charmeleon   Fire
2                   Charizard   Fire
3   CharizardMega Charizard X   Fire
4   CharizardMega Charizard Y   Fire
5                      Vulpix   Fire
6                   Ninetales   Fire
7                   Growlithe   Fire
8                    Arcanine   Fire
9                      Ponyta   Fire
10                   Rapidash   Fire
11                     Magmar   Fire
12                    Flareon   Fire
13                    Moltres   Fire
14                  Cyndaquil   Fire
15                    Quilava   Fire
16                 Typhlosion   Fire
17                     Slugma   Fire
18                   Magcargo   Fire
19                      Magby   Fire
20                      Entei   Fire
21                      Ho-oh   Fire
22                    Torchic   Fire
23                  Combusken   Fire
24                   Blaziken   Fire
25      BlazikenMega Blaziken   Fire
26                      Numel   Fire
27                   Camerupt   Fire
28      CameruptMega Camerupt   Fire
29                    Torkoal   Fire
30                   Chimchar   Fire
31                   Monferno   Fire
32                  Infernape   Fire
33                  Magmortar   Fire
34                    Heatran   Fire
35                      Tepig   Fire
36                    Pignite   Fire
37                     Emboar   Fire
38                    Pansear   Fire
39                   Simisear   Fire
40                   Darumaka   Fire
41    DarmanitanStandard Mode   Fire
42         DarmanitanZen Mode   Fire
43                    Heatmor   Fire
44                   Fennekin   Fire
45                    Braixen   Fire
46                    Delphox   Fire
47                Fletchinder   Fire
48                 Talonflame   Fire
49                     Litleo   Fire
50                     Pyroar   Fire
51                  Volcanion   Fire

In [112]:
# 9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
query = '''
SELECT *
FROM pokemon
WHERE (Defense > 100 ) and name LIKE "W%"
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,1,0
1,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,0

In [113]:
# 10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
query = '''
SELECT *
FROM pokemon
WHERE "Speed" >= 130  and  "Generation" > 0 and "Type 1" <> "Psychic"
'''

sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,0
1,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,0
2,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,0
3,135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,1,0
4,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,0
5,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,0
6,169,Crobat,Poison,Flying,535,85,90,80,70,80,130,2,0
7,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,0
8,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,0
9,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,0
10,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,0
11,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,0

In [114]:
# 11. ¿Cuál es el pokemon con el ataque más alto?
query = '''
SELECT MAX(Attack) "Ataque mas alto", Name
FROM pokemon
'''

sql_query(query)

   Ataque mas alto                 Name
0              190  MewtwoMega Mewtwo X

In [115]:
# 12. ¿Cuál es la media de la defensa de todos los pokemon?
query = '''
SELECT Name "Nombre", AVG(Defense) "Media defensa"
FROM pokemon
'''
sql_query(query)

      Nombre  Media defensa
0  Bulbasaur        73.8425

In [136]:
# 13. ¿Cuál es la media de la defensa por generación?
query = '''
SELECT Generation Generacion, AVG(defense) Media_Defensa
FROM pokemon
GROUP BY Generation
'''

sql_query(query)

   Generacion  Media_Defensa
0           1      70.861446
1           2      73.386792
2           3      74.100000
3           4      78.132231
4           5      72.327273
5           6      76.682927

In [138]:
# Apartado 14. Calcula el máximo HP por "Type 1"
query = '''
SELECT MAX(HP), "Type 1"
FROM pokemon
GROUP BY "Type 1"
'''

sql_query(query)

    MAX(HP)    Type 1
0        86       Bug
1       126      Dark
2       125    Dragon
3        90  Electric
4       126     Fairy
5       144  Fighting
6       115      Fire
7        85    Flying
8       150     Ghost
9       123     Grass
10      115    Ground
11      110       Ice
12      255    Normal
13      105    Poison
14      190   Psychic
15      123      Rock
16      100     Steel
17      170     Water